// This file is generated by mruby-cli. Do not touch.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

/* Include the mruby header */
#include <mruby.h>
#include <mruby/array.h>

static int check_match_owner(int argc, char *argv[]) {
  struct stat buf;
  if (argc <= 2) {
    return 0;
  }
  if (!strcmp(argv[1], "run") && !strcmp(argv[1], "start")) {
    return 0;
  }

  if (stat(argv[argc - 1], &buf)) {
    return 0; // Skip error or non-exist file
  }

  if(geteuid() == buf.st_uid && getegid() == buf.st_gid) {
    return 0; // Success
  }

  return -1; // Error to execute
}

int main(int argc, char *argv[])
{
  mrb_state *mrb = mrb_open();
  mrb_value ARGV = mrb_ary_new_capa(mrb, argc);
  int i;
  int return_value;

#ifdef HACONIWA_SECURE_RUN
  if(check_match_owner(argc, argv) < 0) {
    mrb_raise(mrb, E_RUNTIME_ERROR,
              "haconiwa runner and hacofile's owner would not be matched: This run prohibited on secure-run build");
    exit(2);
  }
#endif

  for (i = 0; i < argc; i++) {
    mrb_ary_push(mrb, ARGV, mrb_str_new_cstr(mrb, argv[i]));
  }
  mrb_define_global_const(mrb, "ARGV", ARGV);

  // call __main__(ARGV)
  mrb_funcall(mrb, mrb_top_self(mrb), "__main__", 1, ARGV);

  return_value = EXIT_SUCCESS;

  if (mrb->exc) {
    mrb_print_error(mrb);
    return_value = EXIT_FAILURE;
  }
  mrb_close(mrb);

  return return_value;
}
