module Haconiwa
  PHASE_START_EVAL   = 1
  PHASE_START_FORK   = 2
  PHASE_END_SETUP    = 3
  PHASE_START_WAIT   = 4
  PHASE_END_WAIT     = 5
  PHASE_CLEANUP      = 6

  PHASE_CONTAINER_START = 11
  PHASE_CONTAINER_NAMESPACE_GENERATED = 12
  PHASE_CONTAINER_FILESYSTEM_SETUP = 13
  PHASE_CONTAINER_RLIMIT_SETUP = 14
  PHASE_CONTAINER_CGROUP_SETUP = 15
  PHASE_CONTAINER_REMOUNTED = 16
  PHASE_CONTAINER_UID_MAPPING_SETUP = 17
  PHASE_CONTAINER_CHROOTED = 18
  PHASE_CONTAINER_CAPABILITY_SETUP = 19
  PHASE_CONTAINER_SECCOMP_SETUP = 20
  PHASE_CONTAINER_EXECING = 21

  PHASE_USR1 = 123
  PHASE_USR2 = 124
  PHASE_USR3 = 125
  PHASE_USR4 = 126
  PHASE_USR5 = 127
end
