module Haconiwa
  PHASE_START_EVAL   = 1
  PHASE_START_FORK   = 2
  PHASE_END_SETUP    = 3
  PHASE_START_WAIT   = 4
  PHASE_END_WAIT     = 5
  PHASE_CLEANUP      = 6

  PHASE_USR1 = 123
  PHASE_USR2 = 124
  PHASE_USR3 = 125
  PHASE_USR4 = 126
  PHASE_USR5 = 127
end
